"use client"

import Head from 'next/head'
import { Inter } from 'next/font/google'
import { useContext, useEffect, useState } from 'react'
import { AppContext } from '@/context/app_context';
import { useRouter } from 'next/router';

const inter = Inter({ subsets: ['latin'] })

export default function Splash() {
  const appContext = useContext(AppContext);
  const router = useRouter()

  useEffect(
    () => {
      if (appContext.repository.getToken() == '') {
        router.push('/login')
      } else {
        router.push('/home')
      }
    }, [])

  return (
    <>
      <Head>
        <title>Ini adalah title</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  )
}
